// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8hHu2WGUEINj1AIuygm-ujJ8lVGk7vNY',
    appId: '1:975485948061:web:48e7c65b62ba2d33f84474',
    messagingSenderId: '975485948061',
    projectId: 'viabilidade-tecnica-trash',
    authDomain: 'viabilidade-tecnica-trash.firebaseapp.com',
    storageBucket: 'viabilidade-tecnica-trash.appspot.com',
    measurementId: 'G-7MBTJZ664Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv0ji9nio_fv7tTiKDU3Tulkzd_hdOUjA',
    appId: '1:975485948061:android:738247bdea984c05f84474',
    messagingSenderId: '975485948061',
    projectId: 'viabilidade-tecnica-trash',
    storageBucket: 'viabilidade-tecnica-trash.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ5RTgO-aPTFUWJY0D9_ygNYmT-823Mzc',
    appId: '1:975485948061:ios:5e3d0b85301f96e8f84474',
    messagingSenderId: '975485948061',
    projectId: 'viabilidade-tecnica-trash',
    storageBucket: 'viabilidade-tecnica-trash.appspot.com',
    iosBundleId: 'com.example.testeTelaLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ5RTgO-aPTFUWJY0D9_ygNYmT-823Mzc',
    appId: '1:975485948061:ios:eec024b56005c19ff84474',
    messagingSenderId: '975485948061',
    projectId: 'viabilidade-tecnica-trash',
    storageBucket: 'viabilidade-tecnica-trash.appspot.com',
    iosBundleId: 'com.example.testeTelaLogin.RunnerTests',
  );
}
